package com.ecommerce.prorider.services.auth;

import com.ecommerce.prorider.entities.auth.Store;
import com.ecommerce.prorider.entities.auth.VerificationToken;
import com.ecommerce.prorider.exceptions.BadRequestException;
import com.ecommerce.prorider.interfaces.auth.IVerificationToken;
import com.ecommerce.prorider.repository.auth.StoreRepository;
import com.ecommerce.prorider.repository.auth.VerificationTokenRepository;

import java.time.LocalDateTime;
import java.util.UUID;

public class VerificationTokenService implements IVerificationToken {

    private final StoreRepository storeRepository;
    private final StoreService storeService;
    private final VerificationTokenRepository verificationTokenRepository;


    public VerificationTokenService(StoreRepository storeRepository, StoreService storeService, VerificationTokenRepository verificationTokenRepository) {
        this.storeRepository = storeRepository;
        this.storeService = storeService;
        this.verificationTokenRepository = verificationTokenRepository;
    }

    @Override
    public VerificationToken createToken(String storeName) {
        /// Find the Store Object
        Store store = storeService.findStoreByStoreName(storeName);
        /// If Store has already a token, rewrite it & call reset password
        verificationTokenRepository.findByStore(store).ifPresent(verificationTokenRepository::delete);
        /// If Store doesn't have a token - create - > VerificationToken Initialization
        VerificationToken token = new VerificationToken();
        /// ID generated by the database
        token.setStore(store);
        token.setExpiresAt(LocalDateTime.now().plusHours(24));
        token.setToken(UUID.randomUUID().toString());
        verificationTokenRepository.save(token);
        return token;
    }

    @Override
    public Boolean authenticateTokenAccount(String token) {
        /// Retrieve the "VerificationToken" object from the database
        VerificationToken verificationToken = verificationTokenRepository.findByToken(token)
                .orElseThrow(() -> new BadRequestException("token was not found on the database"));
        /// Checks if verificationToken is not null
        if (verificationToken == null){
            return false;
        }
        /// Fill the data pending & save the changes
        if (verificationToken.getExpiresAt().isBefore(LocalDateTime.now())) {
            throw new BadRequestException("Token has expired");
        }
        verificationToken.setConfirmedAt(LocalDateTime.now());
        verificationTokenRepository.save(verificationToken);
        /// Edit Store.Enable to True
       Store store = verificationToken.getStore();
       store.setEnable(true);
       storeRepository.save(store);
        return true;
    }
}
